#!/bin/bash
# Create master flat frame from flat frames
# Usage:
# 	master-flat <dir>
# Options:
#	dir	directory of flat frame FITS images

Color_Off="\e[0m"  # Text Reset
BRed="\e[1;31m"    # Red
BGreen="\e[1;32m"  # Green
Blue="\e[0;34m"    # Blue

DEFAULT_FLATDIR="Flat"
FLAT_FILE_PREFIX="Flat_"

echo
echo -e "${BGreen}master-flat, version 0.1.0${Color_Off}"
echo -e "${Blue}create master flat frame.${Color_Off}"
echo

# Declare source and target directories
# TODO: directory of master dark could be parametrized
SOURCEDIR=$([ "$1" = "" ] && echo $DEFAULT_FLATDIR || echo $1)
TARGETDIR=$SOURCEDIR
TEMPDIR="temp"
BIASDIR="Bias"
DARKDIR="Dark"

if [ ! -d $SOURCEDIR ]; then
  echo -e "${BRed}Error: Parameter is not a directory!${Color_Off}"
  exit 1
fi

# Create the temp dir, if not exists
if [ ! -e $TEMPDIR ]; then
  mkdir $TEMPDIR
fi

# Names of the individual files storing the raw bias, dark, flat and object frames:
FLATLIST=($SOURCEDIR/${FLAT_FILE_PREFIX}*.fits)
if [ ! -e ${FLATLIST[0]} ]; then
  echo -e "${BRed}Error: No flat files in the directory.${Color_Off}"
  exit 1
fi

# check existence of master bias file
if [ ! -e $BIASDIR/master-bias.fits ]; then
  echo -e "${BRed}Error: No master-bias file found.${Color_Off}"
  exit 1
fi

# check existence of master dark file
if [ ! -e $DARKDIR/master-dark.fits ]; then
  echo -e "${BRed}Error: No master-dark file found.${Color_Off}"
  exit 1
fi

start=`date +%s`

echo "$SOURCEDIR/${FLAT_FILE_PREFIX}*.fits -> $TARGETDIR/master-flat.fits"

# Calibrated images: all the images have the same name but put into a separate directory ($TARGET):
R_FLATLIST=($(for f in ${FLATLIST[*]} ; do echo ${TEMPDIR}/`basename $f` ; done ))

# Common arguments (saturation level, image section & trimming, etc.):
# TODO: image size from FITS header NAXIS1, NAXIS2
COMMON_ARGS="--saturation 16000 --image 0:0:2144:1427 --trim"

# The calibration of the individual flat frames, followed by their combination into a single master image:
ficalib -i ${FLATLIST[*]} $COMMON_ARGS --post-scale 20000 -o ${R_FLATLIST[*]} \
--input-master-bias $BIASDIR/master-bias.fits --input-master-dark $DARKDIR/master-dark.fits
ficombine ${R_FLATLIST[*]} --mode median -o $SOURCEDIR/master-flat.fits

end=`date +%s`

# remove temp files
for f in ${R_FLATLIST[*]} ; do rm -f $f ; done

echo
echo -e "${Blue}conversion ready."
echo -e "execution time was $((end-start)) seconds.${Color_Off}"

#end.

