#!/bin/bash
# Create master bias frame from bias frames
# Usage:
# 	master-bias <dir>
# Options:
#	dir	directory of bias frame FITS images

Color_Off="\e[0m"  # Text Reset
BRed="\e[1;31m"    # Red
BGreen="\e[1;32m"  # Green
Blue="\e[0;34m"    # Blue

DEFAULT_BIASDIR="Bias"
BIAS_FILE_PREFIX="Bias_"

echo
echo -e "${BGreen}master-bias, version 0.1.0${Color_Off}"
echo -e "${Blue}create master bias frame.${Color_Off}"
echo

# Declare source and target directories
# TODO: directory of master bias could be parametrized
SOURCEDIR=$([ "$1" = "" ] && echo $DEFAULT_BIASDIR || echo $1)
TARGETDIR=$SOURCEDIR
TEMPDIR="temp"

if [ ! -d $SOURCEDIR ]; then
  echo -e "${BRed}Error: Parameter is not a directory!${Color_Off}"
  exit 1
fi

# Create the temp dir, if not exists
if [ ! -e $TEMPDIR ]; then
  mkdir $TEMPDIR
fi

# Names of the individual files storing the raw bias, dark, flat and object frames:
BIASLIST=($SOURCEDIR/${BIAS_FILE_PREFIX}*.fits)
if [ ! -e ${BIASLIST[0]} ]; then
  echo -e "${BRed}Error: No bias files in the directory.${Color_Off}"
  exit 1
fi

start=`date +%s`

echo "$SOURCEDIR/${BIAS_FILE_PREFIX}*.fits -> $TARGETDIR/master-bias.fits"

# Calibrated images: all the images have the same name but put into a separate directory ($TARGET):
R_BIASLIST=($(for f in ${BIASLIST[*]} ; do echo ${TEMPDIR}/`basename $f` ; done ))

# Common arguments (saturation level, image section & trimming, etc.):
# TODO: image size from FITS header NAXIS1, NAXIS2
COMMON_ARGS="--saturation 16000 --image 0:0:2144:1427 --trim"

# The calibration of the individual bias frames, followed by their combination into a single master image:
ficalib -i ${BIASLIST[*]} $COMMON_ARGS -o ${R_BIASLIST[*]}
ficombine ${R_BIASLIST[*]} --mode median -o $TARGETDIR/master-bias.fits

end=`date +%s`

# remove temp files
for f in ${R_BIASLIST[*]} ; do rm -f $f ; done

echo -e "${Blue}conversion ready."
echo -e "execution time was $((end-start)) seconds.${Color_Off}"

#end.

