#!/bin/bash
# Create master dark frame from dark frames
# Usage:
# 	master-dark <dir>
# Options:
#	dir	directory of dark frame FITS images

Color_Off="\e[0m"  # Text Reset
BRed="\e[1;31m"    # Red
BGreen="\e[1;32m"  # Green
Blue="\e[0;34m"    # Blue

DEFAULT_DARKDIR="Dark"
DARK_FILE_PREFIX="Dark_"

echo
echo -e "${BGreen}master-dark, version 0.1.0${Color_Off}"
echo -e "${Blue}create master dark frame.${Color_Off}"
echo

# Declare source and target directories
# TODO: directory of master dark could be parametrized
SOURCEDIR=$([ "$1" = "" ] && echo $DEFAULT_DARKDIR || echo $1)
TARGETDIR=$SOURCEDIR
TEMPDIR="temp"
BIASDIR="Bias"

if [ ! -d $SOURCEDIR ]; then
  echo -e "${BRed}Error: Parameter is not a directory!${Color_Off}"
  exit 1
fi

# Create the temp dir, if not exists
if [ ! -e $TEMPDIR ]; then
  mkdir $TEMPDIR
fi

# Names of the individual files storing the raw bias, dark, flat and object frames:
DARKLIST=($SOURCEDIR/${DARK_FILE_PREFIX}*.fits)
#echo ${DARKLIST[*]}
if [ ! -e ${DARKLIST[0]} ]; then
  echo -e "${BRed}Error: No dark files in the directory.${Color_Off}"
  exit 1
fi

# check existence of master bias file
if [ ! -e $BIASDIR/master-bias.fits ]; then
  echo -e "${BRed}Error: No master-bias file found.${Color_Off}"
  exit 1
fi

start=`date +%s`

echo "$SOURCEDIR/${DARK_FILE_PREFIX}*.fits -> $TARGETDIR/master-dark.fits"

# Calibrated images: all the images have the same name but put into a separate directory ($TARGET):
R_DARKLIST=($(for f in ${DARKLIST[*]} ; do echo ${TEMPDIR}/`basename $f` ; done ))

# Common arguments (saturation level, image section & trimming, etc.):
# TODO: image size from FITS header NAXIS1, NAXIS2
COMMON_ARGS="--saturation 16000 --image 0:0:2144:1427 --trim"

# The calibration of the individual bias frames, followed by their combination into a single master image:
ficalib -i ${DARKLIST[*]} $COMMON_ARGS -o ${R_DARKLIST[*]} --input-master-bias $BIASDIR/master-bias.fits
ficombine ${R_DARKLIST[*]} --mode median -o $TARGETDIR/master-dark.fits

# Calculate average ccd temperature from .cr2 files, and set it into the master dark
sum=0
count=0
for f in $SOURCEDIR/${DARK_FILE_PREFIX}*.cr2 ; do
  IMAGETEMP=`exiftool -s -g $f | grep -i CameraTemperature | sed 's/[^0-9]//g'`
  sum=$(( $sum+$IMAGETEMP ))
  count=$(( $count+1 ))
done
AVGTEMP=$(( ($sum+($count/2))/$count ))
echo "average dark temperature: $AVGTEMP C"

fiheader --append "CCD-TEMP=${AVGTEMP}./CCD Temperature (Celsius)" $TARGETDIR/master-dark.fits

end=`date +%s`

# remove temp files
for f in ${R_DARKLIST[*]} ; do rm -f $f ; done

echo
echo -e "${Blue}conversion ready."
echo -e "execution time was $((end-start)) seconds.${Color_Off}"

#end.

