#!/bin/bash
# Discovery folders
# Usage:
# 	ppl-disco [<dir-pattern>]
# Options:
#	dir	directory pattern for FITS image folders
#	flat-option

Color_Off="\e[0m"  # Text Reset
BRed="\e[1;31m"    # Red
BGreen="\e[1;32m"  # Green
Blue="\e[0;34m"    # Blue

# call setup, and use folder names

SILENT_MODE=0

if [ ! "$PPL_SETUP" == "OK" ] ; then
  SILENT_MODE=1

  echo
  echo -e "${BGreen}ppl-disco, version 0.1.0${Color_Off}"
  echo -e "${Blue}discovery folders.${Color_Off}"
  echo

  . "ppl-setup"
fi

# parameter $1 - flat folders only (0|1)
# parameter $2 - non-flat folders only (0|1)
# parameter $3 - folder pattern


# discover Bias folder
discover_bias_folder() {
  if [ ! "$1" == "" ] ; then
    BIAS_FOLDERS=(*$1*/$BIAS_FOLDER_NAME)
  else
    BIAS_FOLDERS=($BIAS_FOLDER_NAME)
  fi

  if [ ${#BIAS_FOLDERS[@]} == 0 ] ; then
    echo "Error: no Bias folder found; add one, and rerun this script."
    exit 1
  fi

  if [ ! ${#BIAS_FOLDERS[@]} == 1 ] ; then
    echo "Error: more than one Bias folder found; remove on of them, and rerun this script."
    echo "  --> ${BIAS_FOLDERS[@]}"
    exit 1
  fi

  BIAS_FOLDER=${BIAS_FOLDERS[0]}

  if [ ! -d $BIAS_FOLDER ]; then
    echo "Error: Bias folder $BIAS_FOLDER is not exist ot not a directory."
    exit 1
  fi	

  echo "Bias  folder  discovered:" $BIAS_FOLDER
}

# discover Dark folder
discover_dark_folder() {
  if [ ! "$1" == "" ] ; then
    DARK_FOLDERS=(*$1*/$DARK_FOLDER_NAME)
  else
    DARK_FOLDERS=($DARK_FOLDER_NAME)
  fi

  if [ ${#DARK_FOLDERS[@]} == 0 ] ; then
    echo "Error: no Dark folder found; add one, and rerun this script."
    exit 1
  fi

  if [ ! ${#DARK_FOLDERS[@]} == 1 ] ; then
    echo "Error: more than one Dark folder found; remove on of them, and rerun this script."
    echo "  --> ${DARK_FOLDERS[@]}"
    exit 1
  fi

  DARK_FOLDER=${DARK_FOLDERS[0]}

  if [ ! -d $DARK_FOLDER ]; then
    echo "Error: Dark folder $DARK_FOLDER is not exist ot not a directory."
    exit 1
  fi	

  echo "Dark  folder  discovered:" $DARK_FOLDER
}


if [ "$1" == "0" ] ; then

  discover_bias_folder $3

  discover_dark_folder $3

fi

# discover flat bias folder

if [ "$2" == "0" ] ; then

  if [ ! "$3" == "" ] ; then
    FLAT_BIAS_FOLDERS=(*$3*/$FLAT_BIAS_FOLDER_NAME)
  else
    FLAT_BIAS_FOLDERS=($FLAT_BIAS_FOLDER_NAME)
  fi

  if [ ! ${#FLAT_BIAS_FOLDERS[@]} == 1 ] ; then
    echo "Error: more than one Flat Bias folder found; remove on of them, and rerun this script."
    echo "  --> ${FLAT_BIAS_FOLDERS[@]}"
    exit 1
  fi

  if [ ${#FLAT_BIAS_FOLDERS[@]} == 0 ] || [ ! -d ${FLAT_BIAS_FOLDERS[0]} ] ; then
    if [ "$1" == "1" ] ; then
      discover_bias_folder $3
    fi
    FLAT_BIAS_FOLDER=$BIAS_FOLDER
  else
    FLAT_BIAS_FOLDER=${FLAT_BIAS_FOLDERS[0]}
  fi

  echo "Flat Bias folder discovered:" $FLAT_BIAS_FOLDER

# discover flat dark folder

  if [ ! "$3" == "" ] ; then
    FLAT_DARK_FOLDERS=(*$3*/$FLAT_DARK_FOLDER_NAME)
  else
    FLAT_DARK_FOLDERS=($FLAT_DARK_FOLDER_NAME)
  fi

  if [ ! ${#FLAT_DARK_FOLDERS[@]} == 1 ] ; then
    echo "Error: more than one Flat Dark folder found; remove on of them, and rerun this script."
    echo "  --> ${FLAT_DARK_FOLDERS[@]}"
    exit 1
  fi

  if [ ${#FLAT_DARK_FOLDERS[@]} == 0 ] || [ ! -d ${FLAT_DARK_FOLDERS[0]} ] ; then
    if [ "$1" == "1" ] ; then
      discover_dark_folder $3
    fi
    FLAT_DARK_FOLDER=$DARK_FOLDER
  else
    FLAT_DARK_FOLDER=${FLAT_DARK_FOLDERS[0]}
  fi

  echo "Flat Dark folder discovered:" $FLAT_DARK_FOLDER

# discover flat folder

  if [ ! "$3" == "" ] ; then
    FLAT_FOLDERS=(*$3*/$FLAT_FOLDER_NAME)
  else
    FLAT_FOLDERS=($FLAT_FOLDER_NAME)
  fi

  if [ ! ${#FLAT_FOLDERS[@]} == 1 ] ; then
    echo "Error: more than one Flat folder found; remove on of them, and rerun this script."
    echo "  --> ${FLAT_FOLDERS[@]}"
    exit 1
  fi

  if [ ${#FLAT_FOLDERS[@]} == 0 ] ; then
    echo "Error: no Flat folder found; add one, and rerun this script."
    exit 1
  fi

  FLAT_FOLDER=${FLAT_FOLDERS[0]}
  echo "Flat folder discovered:" $FLAT_FOLDER

fi

if [ "$1" == "0" ] ; then

# discovery Light folders

  if [ ! "$3" == "" ] ; then
    LIGHT_FOLDERS=(*$3*/$LIGHT_FOLDER_NAME*)
  else
    LIGHT_FOLDERS=($LIGHT_FOLDER_NAME*)
  fi

  echo "Light folders discovered:" ${LIGHT_FOLDERS[@]}

fi

#end.

