#!/bin/bash
# Convert CR2 raw images to FITS and separate them by color channel onto the same directory
# Usage:
# 	raw2fits <dir>
# Options:
#	dir	directory of CR2 raw images

Color_Off='\033[0m'       # Text Reset
BRed="\e[1;31m"           # Red
BGreen='\033[1;32m'       # Green
Blue='\033[0;34m'         # Blue

echo
echo -e "${BGreen}raw2fits, version 0.1.0${Color_Off}"
echo -e "${Blue}convert cr2 files to fits.${Color_Off}"
echo

# Declare source and target directories
# TODO: directory of master bias could be parametrized
SOURCEDIR=$([ "$1" = "" ] && echo "."|| echo $1)
TARGETDIR=$SOURCEDIR
TEMPDIR="temp"

if [ ! -d $SOURCEDIR ]; then
  echo -e "${BRed}Error: Parameter is not a directory!${Color_Off}"
  exit 1
fi

start=`date +%s`

# list of raw CR2 file in the input directory
RAWFILES=$SOURCEDIR/*.cr2

# for all raw file do the conversion
for rawfile in $SOURCEDIR/*.cr2; do
  FITS_NAME=${rawfile%.*}.fits
  echo "$rawfile -> $FITS_NAME"
  rawtran -c Gi -o $FITS_NAME -B 16 -C '-4 -D' -X '-q 3 -w' $rawfile
  IMAGETEMP=`exiftool -s -g $rawfile | grep -i CameraTemperature | sed 's/[^0-9]//g'`
  fiheader --append "CCD-TEMP=${IMAGETEMP}./CCD Temperature (Celsius)" $FITS_NAME
done

end=`date +%s`

echo
echo -e "${Blue}conversion ready."
echo -e "execution time was $((end-start)) seconds.${Color_Off}"

# end.

